### ISSUE TITLE
"Push File To The Game" is not working anymore when using with BitBurner v2.2.2

### ISSUE THREAD

**Issue by madhyas** [bitburner-official/bitburner-vscode#29]
While working fine when using with version 1.7 of BitBurner,
with the current version of BitBurner available on Steam (v2.2.2) the file upload does not any longer work as intended.
No files are uploaded anymore and the debug console in BitBurner shows the following error for each attempt to push a file from VSCode to BitBurner: 

![image](https://user-images.githubusercontent.com/126122387/220785792-9ec46f2a-64f4-4a21-808a-7af23e4b070a.png)

**Comment by maxbilbow** [comment]
Looks like this might be fixed in the next release? https://github.com/bitburner-official/bitburner-src/commit/4027f2992f6c8fc7a5f4bc95b6c1cc581babd3fe

**Comment by Kimpalajnen** [comment]
> 

Ye it is fixed now

**Comment by altinturk** [comment]
issue still exists on steam v2.2.2. 
command returns this error, maybe is useful:

`command 'ext.bitburner-connector.pushFile' not found`
